// Generated by CoffeeScript 1.10.0
self.GetSysVersionLog = function() {
  HelperForKO.GetJSON(self.urls.FindSysVersionLog, null, function(result) {
    HelperForKO.EachArray2KOArray(result.ResultData.Result, self.sysVersionLogArray);
  });
};

self.VersionLogClick = function(data) {
  var target;
  target = HelperForKO.EachArrayFindTarget(self.sysVersionLogArray(), function(item) {
    return item.PublishVersion() === data.PublishVersion();
  });
  return console.log(target);
};
