source 'https://gems.ruby-china.org'
# ruby 2.2.4




#gem 'spreadsheet','1.1.3'

#操作excel
gem 'axlsx', '~> 2.1.0.pre'
gem 'rubyzip', '~> 1.1.7'


gem 'roo', '~> 2.5', '>= 2.5.1'

# gem 'rubyzip'
# gem 'zip'

# gem 'axlsx' #, git: 'https://github.com/randym/axlsx.git'
#gem 'rubyzip', '~> 1.1.7'
# gem 'rubyzip', :require => 'zip/zip'
# gem 'rubyzip2'
#发邮件
gem 'mail'