// Generated by CoffeeScript 1.10.0
var Helper;

Helper = window["Helper"] || {};

Helper.DateBothSubtraction = function(date1, date2, type, coefficient) {
  var tmpDate, tmpDate1, tmpDate2;
  tmpDate1 = new Date(date1);
  tmpDate2 = new Date(date2);
  tmpDate = tmpDate1 - tmpDate2;
  switch (type) {
    case 'day':
      coefficient = 1;
      break;
    case 'month':
      coefficient = coefficient != null ? coefficient : 30;
      break;
    case 'year':
      coefficient = coefficient != null ? coefficient : 365;
  }
  return tmpDate / (1000 * 3600 * 24 * coefficient);
};

Helper.DateAddition = function(date, type, coefficient) {
  return Helper.DateAddSubComm(date, type, coefficient, 'add');
};

Helper.DateSubtraction = function(date, type, coefficient) {
  return Helper.DateAddSubComm(date, type, coefficient, 'sub');
};

Helper.DateAddSubComm = function(date, type, coefficient, symbol) {
  var tmpDate;
  tmpDate = new Date(date);
  if (symbol === "add") {
    switch (type) {
      case 'second':
        tmpDate.setSeconds(tmpDate.getSeconds() + coefficient);
        break;
      case 'minute':
        tmpDate.setMinutes(tmpDate.getMinutes() + coefficient);
        break;
      case 'hour':
        tmpDate.setHours(tmpDate.getHours() + coefficient);
        break;
      case 'day':
        tmpDate.setDate(tmpDate.getDate() + coefficient);
        break;
      case 'month':
        tmpDate.setMonth(tmpDate.getMonth() + coefficient);
        break;
      case 'year':
        tmpDate.setFullYear(tmpDate.getFullYear() + coefficient);
    }
  } else {
    switch (type) {
      case 'second':
        tmpDate.setSeconds(tmpDate.getSeconds() - coefficient);
        break;
      case 'minute':
        tmpDate.setMinutes(tmpDate.getMinutes() - coefficient);
        break;
      case 'hour':
        tmpDate.setHours(tmpDate.getHours() - coefficient);
        break;
      case 'day':
        tmpDate.setDate(tmpDate.getDate() - coefficient);
        break;
      case 'month':
        tmpDate.setMonth(tmpDate.getMonth() - coefficient);
        break;
      case 'year':
        tmpDate.setFullYear(tmpDate.getFullYear() - coefficient);
    }
  }
  return tmpDate;
};

Helper.FindDaysInMonth = function(year, month) {
  var temp;
  month = parseInt(month, 10);
  temp = new Date(year, month, 0);
  return temp.getDate();
};

Helper.IsPhone = function(data) {
  return data.search(/^1[34587]\d{9}$/) !== -1;
};

Helper.IsChineseName = function(data) {
  return /^[\u4e00-\u9fa5]{2,50}$/.test(data);
};

Helper.IsEmpty = function(data) {
  return data !== '' && (data != null);
};

Helper.IsEmail = function(data) {
  return /^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$/.test(data);
};

Helper.GetQueryString = function(key, url) {
  var result;
  result = (url || location.search).match(new RegExp("[\?\&]" + key + "=([^\&]+)", "i"));
  if (result === null || result.length < 1) {
    return "";
  }
  return result[1];
};
