// Generated by CoffeeScript 1.10.0
var KoModel;

KoModel = function() {
  var self;
  self = this;
  self.urls = {};
  self.Init = function() {
    new YearMonthDaySelect({
      yearInterval: 10,
      yearTitle: '年',
      yearID: 'test_sl_year',
      yearName: 'test_sl_year_name',
      yearClass: 'test_sl_year_class otherclassname',
      monthTitle: '月',
      monthID: 'test_sl_month',
      monthName: 'test_sl_month_name',
      monthClass: 'test_sl_month_class otherclassname',
      dayTitle: '天',
      dayID: 'test_sl_day',
      dayName: 'test_sl_day_name',
      dayClass: 'test_sl_day_class otherclassname'
    });
  };
  self.ShowSL = function() {
    var day, month, year;
    year = $("#test_sl_year option:selected").val();
    month = $("#test_sl_month option:selected").val();
    day = $("#test_sl_day option:selected").val();
    return $("#span").text(year + '-' + month + '-' + day);
  };
  ko.computed(function() {
    self.Init();
  });
};

ko.applyBindings(new KoModel());
