// Generated by CoffeeScript 1.10.0
var YearMonthDaySelect;

YearMonthDaySelect = (function() {
  var KoViewModel, gParams, koTemplateA, koTemplateB;

  gParams = {};

  function YearMonthDaySelect(args) {
    gParams = args;
  }

  koTemplateA = '<div data-bind="template:{name:\'sl_year_month_day\',data:yearObj}"></div> <div data-bind="template:{name:\'sl_year_month_day\',data:monthObj}"></div> <div data-bind="template:{name:\'sl_year_month_day\',data:dayObj}"></div> <script type="text/template" id="sl_year_month_day"> <select data-bind="attr:{id:$data.id,name:$data.name,class:$data.class},event:{change:$data.changeEvent},foreach:$data.dataArray,selectedOptions:[$data.selectedValue]"> <option data-bind="value:$data.key,text:$data.value"></option> </select> <span data-bind="text:$data.title"></span> </script>';

  koTemplateB = '<div data-bind="template:{name:\'sl_year_month_day\',data:yearObj}"></div> <div data-bind="template:{name:\'sl_year_month_day\',data:monthObj}"></div> <script type="text/template" id="sl_year_month_day"> <select data-bind="attr:{id:$data.id,name:$data.name,class:$data.class},event:{change:$data.changeEvent},foreach:$data.dataArray,selectedOptions:[$data.selectedValue]"> <option data-bind="value:$data.key,text:$data.value"></option> </select> <span data-bind="text:$data.title"></span> </script>';

  KoViewModel = function(params) {
    var selfVM;
    selfVM = this;
    selfVM.yearObj = ko.observableArray();
    selfVM.monthObj = ko.observableArray();
    selfVM.dayObj = ko.observableArray();
    selfVM.GenerateYearArray = function(defaultValue) {
      var i, j, ref, ref1, tmpDataArray, tmpDate, tmpInterval, tmpYear, tmpYearClass, tmpYearID, tmpYearName, tmpYearTitle;
      tmpDate = new Date();
      tmpDataArray = [];
      tmpInterval = gParams.yearInterval != null ? gParams.yearInterval : 5;
      for (i = j = ref = tmpDate.getFullYear() - tmpInterval, ref1 = tmpDate.getFullYear() + tmpInterval; ref <= ref1 ? j < ref1 : j > ref1; i = ref <= ref1 ? ++j : --j) {
        tmpDataArray.push({
          key: i,
          value: i
        });
      }
      tmpYearTitle = gParams.yearTitle != null ? gParams.yearTitle : '年';
      tmpYearID = gParams.yearID != null ? gParams.yearID : 'sl_year';
      tmpYearName = gParams.yearName != null ? gParams.yearName : 'sl_year_name';
      tmpYearClass = gParams.yearClass != null ? gParams.yearClass : 'sl_year_class';
      tmpYear = {
        title: tmpYearTitle,
        id: tmpYearID,
        name: tmpYearName,
        "class": tmpYearClass,
        changeEvent: selfVM.ChangeYear,
        selectedValue: defaultValue,
        dataArray: tmpDataArray
      };
      return selfVM.yearObj(tmpYear);
    };
    selfVM.GenerateMonthArray = function(defaultValue) {
      var i, j, tmpDataArray, tmpMonth, tmpMonthClass, tmpMonthID, tmpMonthName, tmpMonthTitle;
      tmpDataArray = [];
      for (i = j = 1; j <= 12; i = ++j) {
        tmpDataArray.push({
          key: i,
          value: i
        });
      }
      tmpMonthTitle = gParams.monthTitle != null ? gParams.monthTitle : '月';
      tmpMonthID = gParams.monthID != null ? gParams.monthID : 'sl_month';
      tmpMonthName = gParams.monthName != null ? gParams.monthName : 'sl_month_name';
      tmpMonthClass = gParams.monthClass != null ? gParams.monthClass : 'sl_month_class';
      tmpMonth = {
        title: tmpMonthTitle,
        id: tmpMonthID,
        name: tmpMonthName,
        "class": tmpMonthClass,
        changeEvent: selfVM.ChangeMonth,
        selectedValue: defaultValue,
        dataArray: tmpDataArray
      };
      return selfVM.monthObj(tmpMonth);
    };
    selfVM.GenerateDayArray = function(year, month, defaultValue) {
      var i, j, ref, tmpDataArray, tmpDay, tmpDayClass, tmpDayID, tmpDayName, tmpDayTitle;
      tmpDataArray = [];
      for (i = j = 1, ref = "" + (Helper.FindDaysInMonth(year, month)); 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
        tmpDataArray.push({
          key: i,
          value: i
        });
      }
      tmpDayTitle = gParams.dayTitle != null ? gParams.dayTitle : '日';
      tmpDayID = gParams.dayID != null ? gParams.dayID : 'sl_day';
      tmpDayName = gParams.dayName != null ? gParams.dayName : 'sl_day_name';
      tmpDayClass = gParams.dayClass != null ? gParams.dayClass : 'sl_day_class';
      tmpDay = {
        title: tmpDayTitle,
        id: tmpDayID,
        name: tmpDayName,
        "class": tmpDayClass,
        changeEvent: selfVM.ChangeDay,
        selectedValue: defaultValue,
        dataArray: tmpDataArray
      };
      return selfVM.dayObj(tmpDay);
    };
    selfVM.ChangeYear = function(arg) {
      selfVM.GenerateMonthArray(1);
      return selfVM.GenerateDayArray($("#" + arg.id + " option:selected").val(), 1, 1);
    };
    selfVM.ChangeMonth = function(arg) {
      return selfVM.GenerateDayArray($("#" + arg.id + " option:selected").val(), 1, 1);
    };
    selfVM.ChangeDay = function(arg) {};
    selfVM.Init = function() {
      var tmpDate, tmpDay, tmpMonth, tmpYear;
      if (gParams.initYear || gParams.initMonth || gParams.initDay) {
        selfVM.GenerateYearArray(gParams.initYear);
        selfVM.GenerateMonthArray(gParams.initMonth);
        return selfVM.GenerateDayArray(gParams.initYear, gParams.initMonth, gParams.initDay);
      } else {
        tmpDate = new Date();
        tmpYear = tmpDate.getFullYear();
        selfVM.GenerateYearArray(tmpYear);
        if (gParams.initSelect) {
          tmpMonth = tmpDate.getMonth() + 1;
          tmpDay = tmpDate.getDate();
          selfVM.GenerateMonthArray(tmpMonth);
          return selfVM.GenerateDayArray(tmpYear, tmpMonth, tmpDay);
        } else {
          selfVM.GenerateMonthArray(1);
          return selfVM.GenerateDayArray(tmpYear, 1, 1);
        }
      }
    };
    return selfVM.Init();
  };

  ko.components.register('year_month_day_select_a', {
    template: koTemplateA,
    viewModel: function(params) {
      return KoViewModel(params);
    }
  });

  ko.components.register('year_month_day_select_b', {
    template: koTemplateB,
    viewModel: function(params) {
      return KoViewModel(params);
    }
  });

  return YearMonthDaySelect;

})();
