// Generated by CoffeeScript 1.10.0
var KoModel;

KoModel = function() {
  var self;
  self = this;
  self.urls = {};
  self.yearObj = ko.observableArray();
  self.monthObj = ko.observableArray();
  self.dayObj = ko.observableArray();
  self.GenerateYearArray = function(defaultValue) {
    var i, j, ref, ref1, tmpDataArray, tmpDate, tmpYear;
    tmpDate = new Date();
    tmpDataArray = [];
    for (i = j = ref = tmpDate.getFullYear() - 5, ref1 = tmpDate.getFullYear() + 5; ref <= ref1 ? j < ref1 : j > ref1; i = ref <= ref1 ? ++j : --j) {
      tmpDataArray.push({
        key: i,
        value: i
      });
    }
    tmpYear = {
      id: 'sl_year',
      name: 'sl_year_name',
      "class": 'sl_year_class',
      selectedValue: defaultValue,
      dataArray: tmpDataArray
    };
    return self.yearObj = tmpYear;
  };
  self.GenerateMonthArray = function(defaultValue) {
    var i, j, tmpDataArray, tmpMonth;
    tmpDataArray = [];
    for (i = j = 1; j <= 12; i = ++j) {
      tmpDataArray.push({
        key: i,
        value: i
      });
    }
    tmpMonth = {
      id: 'sl_month',
      name: 'sl_month_name',
      "class": 'sl_month_class',
      selectedValue: defaultValue,
      dataArray: tmpDataArray
    };
    return self.monthObj = tmpMonth;
  };
  self.GenerateDayArray = function(year, month, defaultValue) {
    var i, j, ref, tmpDataArray, tmpDay;
    tmpDataArray = [];
    for (i = j = 1, ref = "" + (Helper.FindDaysInMonth(year, month)); 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
      tmpDataArray.push({
        key: i,
        value: i
      });
    }
    tmpDay = {
      id: 'sl_day',
      name: 'sl_day_name',
      "class": 'sl_day_class',
      selectedValue: defaultValue,
      dataArray: tmpDataArray
    };
    return self.dayObj = tmpDay;
  };
  self.Init = function() {
    self.GenerateYearArray(2015);
    self.GenerateMonthArray(5);
    self.GenerateDayArray(2015, 2, 27);
  };
  ko.computed(function() {
    self.Init();
  });
};

ko.applyBindings(new KoModel());
